### GENERAL SETTINGS ###

# Site settings
title: SHIMMERCAT
description: "ShimmerCat is a disruptive web accelerator solution that help e-commerce reduce loading times with 30-60%."
analytics: #Google analytics code in the format XX-nnnnnnnn-n
baseurl: "" #important: start with /
url: "http://www.shimmercat.com"

# Build settings
markdown: kramdown
permalink: /:categories/:title
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is

colors:  #in hex code if not noted else
  primary: "#f67031" #"#F70031"
  primary_rgb: "246,112,49" #"247,0,49" #rgb of the primary. Needed in some places for the transparency effect.
  secondary: "#384452" #"#33004D"
  link: "#428bca"
  link_hover: "#01b2fe"
  footer_heading: "#ffffff"
  footer_content: "#bfc9d3"

# Making projects separate from posts
collections:
  projects:
    output: true
    permalink: /projects/:title/
  questions:
    output: true
    permalink: /questions/:title/

### CONTACT SETTINGS ###

# Social networks usernames. Many more available: google-plus, flickr, linkedin, etc). Shown in footer.
social:
  - title: linkedin
    url: https://se.linkedin.com/company/shimmercat
  - title: facebook
    url: https://www.facebook.com/shimmercatbusiness/
  - title: twitter
    url: https://twitter.com/shimmercat_b2b?lang=en

# Postal address (add as many lines as necessary). Shown in footer and on Contact page.
address:
  - lines:
    - Norra Obbolavägen 112A,
    - 904 22, Umeå,
    - Sweden.
email: ops@shimmercat.com
tel: +4670 485 1947


### GENERAL DATA FOR VARIOUS LOCATIONS ###

# Members information. Shown on About page.
members:
  - name: Mark Webber
    position: CEO
    text: Lorem Ipsum is simply dummy text of the printing and typesetting industry.
    img: team01.jpg
    social:
      - title: envelope #use for email address
        url: mailto:name@domain.com
      - title: twitter
        url: http://twitter.com/handle
  - name: Paul Jameson
    position: Lead Designer
    text: Lorem Ipsum is simply dummy text of the printing and typesetting industry.
    img: team02.jpg
    social:
      - title: envelope #use for email address
        url: mailto:name@domain.com
      - title: twitter
        url: http://twitter.com/handle
  - name: Laura Sommers
    position: Lead Developer
    text: Lorem Ipsum is simply dummy text of the printing and typesetting industry.
    img: team03.jpg
    social:
      - title: envelope #use for email address
        url: mailto:name@domain.com
      - title: twitter
        url: http://twitter.com/handle
  - name: Martin Blunt
    position: Marketing
    text: Lorem Ipsum is simply dummy text of the printing and typesetting industry.
    img: team04.jpg
    social:
      - title: envelope #use for email address
        url: mailto:name@domain.com
      - title: twitter
        url: http://twitter.com/handle
  - name: Martin Blunt
    position: Marketing
    text: Lorem Ipsum is simply dummy text of the printing and typesetting industry.
    img: team04.jpg
    social:
      - title: envelope #use for email address
        url: mailto:name@domain.com
      - title: twitter
        url: http://twitter.com/handle


# Clients information. Shown on Home and About pages.
clients:
  - name: 
    img: client_blank.png
  - name: Outdoorexperten
    img: client01.png
  - name: Easytryck
    img: client02.png
  #- name: RiviaSports
  #  img: client03.png

# Short text about your company. Shown in footer on every page and also separately on Home and Contact page.
about: "ShimmerCat provides an automatic way of going beyond handmade conventional optimizations, at a fraction of the cost and with transparent results. Are you ready for the future of web accelerators?"

# Testimonial content. Shown on Home and About page.
testimonial:
    message: "We have experienced huge speed improvement compared to previous solutions, and at the same time our manual work with reducing loading times has disappeared."
    author: Rickard Sandberg
    position: CEO - EASY ONLINE STORES AB
